services:
  frontend-user:
    build: 
     context: .
     args:
         - VITE_API_URL=http://backend:3000
    environment:
      - VITE_API_URL=http://backend:3000 
    container_name: frontend_user
    ports:
      - "5173:80"
    read_only: true
    tmpfs:
      - /var/cache/nginx:uid=101,gid=101
      - /var/log/nginx:uid=101,gid=101
      - /var/run:uid=101,gid=101
      - /tmp:uid=101,gid=101
    restart: unless-stopped
    networks:
      - ticket-net
    
networks:
  ticket-net:
    external: true
    name: ticket-net